"use client";
import { useState } from "react";
import { useParams } from "next/navigation";

const profiles:Record<string,{name:string;roman:string;age:string;kind:string;enKind:string;role:string;enRole:string;tone:string;intro:string;enIntro:string;story:string;enStory:string}>={
 yuuhi:{name:"纁",roman:"YUUHI",age:"19",kind:"魷魚 · 男",enKind:"Inkling · Male",role:"熊先生商會打工仔",enRole:"Grizzco Worker",tone:"orange",intro:"隨和、缺乏自信，卻總會努力回應他人的善意。",enIntro:"Easygoing and insecure, yet always determined to return every kindness.",story:"母親早逝後，纁在父親的暴力與賭債下長大。十四歲那年父親失蹤，把所有債務留給他。他被迫輟學，進入熊先生商會工作；多年後已熟悉所有地圖，卻把象徵成就的徽章全都賣掉換錢。",enStory:"After losing his mother, Yuuhi grew up under his father's violence and gambling debts. At fourteen his father vanished, leaving everything behind. Forced out of school and into Grizzco, he mastered every map—then sold every badge he earned to survive."},
 musubi:{name:"結",roman:"MUSUBI",age:"21",kind:"章魚 · 女",enKind:"Octoling · Female",role:"黑客／前軍官",enRole:"Hacker / Former Officer",tone:"pink",intro:"熱情開放、主動出擊，對喜歡的人和事絕不放手。",enIntro:"Open, passionate, and relentless about the people and things she loves.",story:"軍人家庭出身，在情報處理和技術開發方面表現出色。來到地面偵察時脫隊，黑進軍方系統抹去自己的全部資料。某夜醉倒街頭，被纁撿回家照顧，從此開始同居。",enStory:"Raised by military parents, Musubi excelled at intelligence and technology. During a surface mission she deserted and hacked the military system to erase herself. One drunken night, Yuuhi found her in the street—and their life together began."},
 shuu:{name:"終",roman:"SHUU",age:"24",kind:"章魚 · 男",enKind:"Octoling · Male",role:"真格選手／前軍官",enRole:"Ranked Player / Former Officer",tone:"teal",intro:"冷靜沉穩，親和力強，笑容背後總帶著一點距離。",enIntro:"Calm and charming, with a smile that always keeps others at a careful distance.",story:"十四歲進入軍校，十八歲已成為長官。二十二歲執行地面偵察任務時選擇脫隊，在真格比賽中建立名聲與財富。他一面調查熊先生商會，一面尋找先後來到地面的妹妹結。",enStory:"Shuu entered military school at fourteen and became an officer by eighteen. At twenty-two he deserted during a surface mission, building fame and wealth in ranked battles while investigating Grizzco and searching for his sister."},
 sumire:{name:"堇",roman:"SUMIRE",age:"23",kind:"章魚 · 女",enKind:"Octoling · Female",role:"軍醫",enRole:"Military Doctor",tone:"violet",intro:"陰沉少話、醫術高明，對每一位患者都全力救治。",enIntro:"Quiet and severe, but a brilliant doctor who fights for every patient.",story:"堇自小便對生物與人體充滿興趣，進入軍校研讀醫學後成為技術精準的軍醫。她與因任務受傷的結相識並交往，分手多年後仍無法接受那段關係已經結束。",enStory:"Fascinated by anatomy from childhood, Sumire studied medicine and became a precise military doctor. She met Musubi while treating her injuries; years after their breakup, she still cannot accept that it is over."},
 akane:{name:"茜",roman:"AKANE",age:"24",kind:"魷魚 · 女",enKind:"Inkling · Female",role:"真格選手",enRole:"Ranked Player",tone:"red",intro:"熱情開朗、親和力十足，在愛情路上屢敗屢戰。",enIntro:"Bright, friendly, and forever ready to try love one more time.",story:"身為水果店長女，茜從小幫忙照顧四個弟妹。終於有時間追尋真愛後，她在失戀當天的真格比賽遇見終。心動雖然沒有結果，兩人卻成了默契絕佳的固定隊友。",enStory:"The eldest daughter of a fruit-shop family, Akane grew up caring for four siblings. She met Shuu in a ranked battle on the day of a breakup. Her crush went nowhere, but they became an exceptional team."},
 kumori:{name:"曇",roman:"KUMORI",age:"22",kind:"魷魚 · 女",enKind:"Inkling · Female",role:"紡織企業千金",enRole:"Textile Heiress",tone:"pearl",intro:"溫婉隨和、舉止優雅，是纁失聯多年的青梅竹馬。",enIntro:"Gentle and graceful, she is Yuuhi's long-lost childhood friend.",story:"十歲時，曇在慈善活動中遇見躲在公園哭泣的纁，兩人成為朋友。兩年後她因家族生意搬走，未能親口道別。成年後來到蠻頹鎮，終於和纁重逢。",enStory:"At ten, Kumori found Yuuhi crying alone in a park during a charity visit. They became friends, but she moved away two years later without saying goodbye. As an adult, she finally finds him again in Splatsville."}
};
export default function CharacterPage(){const {slug}=useParams<{slug:string}>();const p=profiles[slug]||profiles.yuuhi;const [lang,setLang]=useState<"zh"|"en">("zh"),en=lang==="en";return <main className={`detail ${p.tone}`}><nav className="nav"><a className="brand" href="/"><span>CITRUSODA</span> OC ARCHIVE</a><button className="lang" onClick={()=>setLang(en?"zh":"en")}><span className={!en?"on":""}>中</span><span className={en?"on":""}>EN</span></button></nav><a className="back" href="/">← {en?"BACK TO ARCHIVE":"返回角色檔案"}</a><section className="detail-grid"><div className="portrait detail-portrait"><span>{p.name}</span><small>{p.roman}</small></div><article><div className="kicker">CHARACTER PROFILE / {p.roman}</div><h1>{p.name}<i>{p.roman}</i></h1><div className="stats"><span><small>AGE</small>{p.age}</span><span><small>SPECIES</small>{en?p.enKind:p.kind}</span><span><small>ROLE</small>{en?p.enRole:p.role}</span></div><h2>{en?"PERSONALITY":"人物個性"}</h2><p>{en?p.enIntro:p.intro}</p><h2>{en?"BACKGROUND":"背景故事"}</h2><p>{en?p.enStory:p.story}</p></article></section></main>}
