"use client";
import {useSiteLanguage} from "../../useSiteLanguage";
import {useParams} from "next/navigation";
import {sitePath} from "../../sitePath";
const profiles:any={
 yuuhi:{name:"纁",roman:"YUUHI",age:"19",height:"175cm",species:"魷魚",enSpecies:"Inkling",sex:"男",enSex:"Male",job:"熊先生商會打工仔",enJob:"Grizzco Worker",weapon:"工作刮水刀",enWeapon:"Splatana Stamper",tone:"orange",intro:"隨和、缺乏自信；會努力回應來自他人的好意和喜歡。因高強度打工而長期缺乏睡眠，對打工以外的事情也有點遲鈍。",enIntro:"Easygoing and insecure, Yuuhi always tries to return the kindness and affection he receives. Long Grizzco shifts leave him sleep-deprived and rather slow to notice anything outside work.",story:"母親在他兩歲時因病離世，父親自此性情大變，沉迷賭博並把情緒發洩在纁身上。十四歲生日當天，父親留下多年賭債後失蹤；纁被迫輟學，開始在熊先生商會打工還債。",enStory:"Yuuhi's mother died when he was two. His grieving father became violent, fell into gambling, and accumulated enormous debts. On Yuuhi's fourteenth birthday his father disappeared, leaving every debt behind; Yuuhi had to leave school and work for Grizzco to repay them.",extra:[
  {zh:"外觀設定",en:"Appearance",zhItems:["髮型：以海藍色髮圈綁成低馬尾，頭上有兩條翹毛。","墨水顏色：橘色漸變藍紫。","眼睛顏色：海藍。","常服：燃料外套、白色襯衫、藍色無袖背心及 Oyster 甘露醬油鞋。"],enItems:["Hair: A low ponytail tied with a sea-blue band, with two loose tufts on top.","Ink color: Orange fading into blue-violet.","Eye color: Ocean blue.","Everyday outfit: Fuel jacket, white shirt, blue sleeveless vest, and Oyster shoes."]},
  {zh:"經歷",en:"History",zhItems:["剛開始打工時因不熟練而經常遍體鱗傷；後來所有地圖均達到傳說 999，但把徽章全部賣掉換錢。","原本一家居住在尚興地區。十八歲時，纁為了較便宜的房租，獨自搬到蠻頹鎮。"],enItems:["He was often badly injured when he first started working. He later reached Eggsecutive VP 999 on every map, but sold all his badges for money.","His family originally lived in Inkopolis. At eighteen, he moved alone to Splatsville for cheaper rent."]}
 ]},
 musubi:{name:"結",roman:"MUSUBI",age:"21",height:"165cm",species:"章魚",enSpecies:"Octoling",sex:"女",enSex:"Female",job:"黑客",enJob:"Hacker",weapon:"桶裝旋轉槍",enWeapon:"Heavy Splatling",tone:"pink",intro:"熱情開放、主動出擊，擅長撒嬌和耍任性；對喜歡的人和事情絕不放手。",enIntro:"Open, passionate, and proactive. Musubi knows how to act spoiled and stubborn, and never lets go of the people or things she loves.",story:"結出身軍人家庭，曾是章魚軍隊軍官。二十一歲獲選參與地面偵察後脫隊，黑進軍隊系統消除自己的全部檔案。來到地面一個月後，她醉倒街頭，被晚歸的纁帶回家照顧，從此與他同居。",enStory:"Born into a military family, Musubi became an Octarian officer. At twenty-one she deserted during a surface reconnaissance mission and hacked the military system to erase her records. A month later, Yuuhi found her drunk and asleep in the street, brought her home, and she stayed as his housemate.",extra:[
  {zh:"外觀設定",en:"Appearance",zhItems:["髮型：中分；兩條觸手在後腦打成一個結，另兩條自然垂下。","墨水顏色：粉紅漸變青綠。","眼睛顏色：金色，配深粉色瞳孔。","常服：無袖襯衫、粉紅蝴蝶結、粉紅短裙、卡其色外套及燒河豚拖鞋。"],enItems:["Hair: Center-parted; two tentacles tied into a knot at the back, with two hanging naturally.","Ink color: Pink fading into turquoise.","Eye color: Gold with deep-pink pupils.","Everyday outfit: Sleeveless shirt, pink bow and skirt, khaki coat, and Fried Fish Slides."]},
  {zh:"喜好",en:"Likes",zhItems:["甜食、打扮、時尚、電腦，以及纁。"],enItems:["Sweets, dressing up, fashion, computers, and Yuuhi."]},
  {zh:"經歷",en:"History",zhItems:["十四歲入讀軍校，在情報處理和技術開發方面表現優異。","十八歲與軍醫堇交往，二十歲分手。","她有一位名為終的哥哥；兄妹自小感情很好，終比她早兩年來到地面。"],enItems:["She entered military school at fourteen and excelled in information processing and technical development.","She began dating the military doctor Sumire at eighteen; they separated when she was twenty.","Her older brother Shuu was also an officer. The siblings have always been close, and he reached the surface two years before her."]}
 ]},
 shuu:{name:"終",roman:"SHUU",age:"24",height:"188cm",species:"章魚",enSpecies:"Octoling",sex:"男",enSex:"Male",job:"真格選手",enJob:"Ranked Player",weapon:"遠距爆破槍",enWeapon:"Range Blaster",tone:"teal",intro:"冷靜沉穩，臉上總掛著笑容，卻多半是皮笑肉不笑。親和力強、擅長社交，但總給人淡淡的距離感。",enIntro:"Calm and steady, Shuu almost always wears a smile—though rarely a sincere one. He is sociable and approachable, yet maintains a subtle emotional distance.",story:"終自幼接受軍人父母的嚴格訓練，入伍後很快晉升為長官。二十二歲執行地面偵察任務時，他因嚮往地面的自由而脫隊，靠真格比賽生活。他亦暗中調查熊先生商會，並在那裡認識纁；找到妹妹結後，才發現她正與纁同居。",enStory:"Shuu was strictly trained by his military parents and rose quickly to become an officer. During a surface reconnaissance mission at twenty-two, he deserted in search of freedom and began earning a living through ranked battles. He also investigated Grizzco in secret, where he met Yuuhi—and later discovered that his missing sister Musubi was living with him.",extra:[
  {zh:"外觀設定",en:"Appearance",zhItems:["髮型：綁成兩條低馬尾，一條自然垂落，另一條搭在肩膀上。","墨水顏色：粉色漸變青綠。","眼睛顏色：金色，配深粉色瞳孔。","常服：高領黑色 T-shirt、卡其色大衣及章魚戰士靴。"],enItems:["Hair: Two low ponytails, one hanging naturally and one resting over his shoulder.","Ink color: Pink fading into turquoise.","Eye color: Gold with deep-pink pupils.","Everyday outfit: Black high-neck T-shirt, khaki coat, and Octoling boots."]},
  {zh:"經歷",en:"History",zhItems:["十四歲入讀軍校，成績名列前茅並以優等生身份畢業；十八歲成為長官，負責指揮部隊及訓練部下。","來到地面後迅速建立人脈，多次嘗試聯絡身在地底的結，但一直失敗。","作為優秀的真格選手，他很快獲得贊助商青睞，偶爾替品牌代言；加上豐厚比賽獎金，很快累積了可觀財富。"],enItems:["He entered military school at fourteen, graduated with top honors, and became an officer at eighteen, commanding units and training subordinates.","On the surface he quickly built a network and repeatedly tried—but failed—to contact Musubi underground.","His ranked-battle skill soon attracted sponsors and endorsement work. Together with prize money, this allowed him to build considerable wealth."]}
 ]},
 sumire:{name:"堇",roman:"SUMIRE",age:"23",height:"168cm",species:"章魚",enSpecies:"Octoling",sex:"女",enSex:"Female",job:"軍醫",enJob:"Military Doctor",weapon:"特務配件",enWeapon:"Undercover Brella",tone:"violet",intro:"陰沉少話、佔有慾強，在醫術上極具天賦。雖然不善社交，卻會全力救治每一位患者，這是她作為醫生的尊嚴與自我要求。",enIntro:"Quiet, withdrawn, and intensely possessive, Sumire has an exceptional gift for medicine. Although she avoids socializing, she gives every patient her full effort—an essential part of her pride and discipline as a doctor.",story:"堇自小對生物身體抱有強烈興趣，甚至會偷偷剪下同伴的觸手研究。家人發現她的天賦後，把她送入軍校研讀醫學；她以優異成績畢業，成為地下章魚軍隊的軍醫。結在任務中受傷時由堇治療，兩人後來開始交往；但結無法承受她過度癡情和過激的行為，最終提出分手。結前往地面後再沒有回來，堇也追到地面尋找她。",enStory:"Sumire showed an intense fascination with anatomy from childhood, even secretly cutting samples from other Octolings' tentacles for study. Recognizing her talent, her family sent her to military school to study medicine. She graduated with outstanding results and became a doctor in the underground Octarian army. She met Musubi while treating an injury sustained on a mission, and the two later began dating. Musubi eventually ended the relationship because of Sumire's obsessive and extreme behavior. When Musubi left for the surface and never returned, Sumire followed in search of her.",extra:[
  {zh:"外觀設定",en:"Appearance",zhItems:["髮型：兩條觸手束成高馬尾，其中一條前髮蓋過半邊臉。","墨水顏色：藍紫漸變粉紫。","眼睛顏色：白色。","常服：高領黑色緊身裙、醫生袍及章魚戰士軍靴。"],enItems:["Hair: Two tentacles tied into a high ponytail, with one front lock covering half her face.","Ink color: Blue-violet fading into pink-violet.","Eye color: White.","Everyday outfit: A fitted black high-neck dress, doctor's coat, and Octoling military boots."]}
 ]},
 akane:{name:"茜",roman:"AKANE",age:"24",height:"165cm",species:"魷魚",enSpecies:"Inkling",sex:"女",enSex:"Female",job:"真格選手",enJob:"Ranked Player",weapon:"濺渡槍",enWeapon:"Dapple Dualies",tone:"red",intro:"熱情開朗、大咧咧，親和力很高。她是個屢敗屢戰的戀愛腦，總是很容易喜歡上別人，卻又不斷在愛情路上碰壁。",enIntro:"Warm, cheerful, easygoing, and naturally approachable. Akane is a hopeless romantic who falls for people quickly, yet somehow keeps running into disappointment.",story:"茜家中經營水果店，她是長女，下面有三個妹妹和一個弟弟。學生時期，她常常幫父母照顧弟妹和店舖，因此錯過了不少體驗。受到電視劇與少女漫畫影響，她一直希望談一場轟轟烈烈的戀愛。弟妹長大後，她終於有時間尋找真愛，甚至會參加真格比賽來認識對象，卻總遇上出軌或後來坦白更喜歡男性的男友。某次被前男友甩掉後，她在比賽中失誤，被同隊的終救下並對他一見鍾情；得知終喜歡男性後，兩人仍因絕佳默契成為朋友與固定隊友。",enStory:"Akane is the eldest daughter of a family that runs a fruit shop, with three younger sisters and one younger brother. She spent much of her school life helping her parents care for her siblings and the shop, missing many ordinary experiences. Inspired by television dramas and girls' manga, she dreams of a sweeping romance. Once her siblings became independent, she began searching for true love—even using ranked battles to meet people—but repeatedly encountered unfaithful boyfriends or partners who later admitted they preferred men. After one breakup, she made a mistake during a match and was rescued by her teammate Shuu. She fell for him immediately, only to learn that he was gay. Their battle coordination was excellent, however, and they became close friends and regular teammates."},
 kumori:{name:"曇",roman:"KUMORI",age:"22",height:"160cm",species:"魷魚",enSpecies:"Inkling",sex:"女",enSex:"Female",job:"紡織企業千金",enJob:"Textile Heiress",weapon:"三發獵魚弓",enWeapon:"Tri-Stringer",tone:"pearl",intro:"溫婉隨和、待人有禮，行為舉止優雅。她是纁失聯多年的青梅竹馬。",enIntro:"Gentle, easygoing, courteous, and graceful. She is Yuuhi's long-lost childhood friend.",story:"曇出身紡織企業家族，是家中長女；她有一位年長七歲、身為繼承人的哥哥，兄妹因哥哥經常為家族事業奔波而甚少交流。十歲時，曇跟隨家族到平民區參與慈善活動，在公園遇見剛被父親打罵、躲在角落哭泣的纁。她上前關心，兩人自此成為朋友，曇也會偶爾偷跑出去找他玩。後來家族拓展生意，她隨家人搬往其他地區，未能與纁道別。成年後，她跟隨家人來到蠻頹鎮，終於與纁重逢，卻發現他的身邊多了兩個章魚。",enStory:"Kumori is the eldest daughter of a family that owns a large textile company. Her brother, seven years older and heir to the business, is often away on family work, so the siblings rarely have time together. At ten, Kumori joined a family charity visit to a working-class neighborhood and found Yuuhi crying alone in a park after being struck and scolded by his father. She comforted him, and the two became friends; she would sometimes sneak out to play with him. When the family business expanded, she moved away without getting a chance to say goodbye. As an adult she came to Splatsville with her family and finally reunited with Yuuhi—only to find two Octolings now beside him.",extra:[
  {zh:"外觀設定",en:"Appearance",zhItems:["髮型：兩條長髮以緞帶綁成低馬尾。","墨水顏色：白色漸變粉色。","眼睛顏色：粉色。"],enItems:["Hair: Two long tentacles tied into low ponytails with ribbons.","Ink color: White fading into pink.","Eye color: Pink."]}
 ]}
};
const order=Object.keys(profiles);
export default function CharacterPage(){
 const {slug}=useParams<{slug:string}>();
 const id=profiles[slug]?slug:"yuuhi",p=profiles[id];
 const {lang,en,setLang}=useSiteLanguage();
 return <main className={`detail profile-page ${p.tone} ${en?"language-en":"language-zh"}`}>
  <nav className="nav"><a className="brand" href={sitePath("/")}><span>CITRUSODA</span> OC ARCHIVE</a><button className="lang" onClick={()=>setLang(en?"zh":"en")}><span className={!en?"on":""}>中</span><span className={en?"on":""}>EN</span></button></nav>
  <a className="profile-back" href={sitePath("/")}>&lt; {en?"Back to home page":"返回首頁"}</a>
  <section className="profile-frame">
   <aside className="profile-icons" aria-label="Choose character">{order.map(x=><a key={x} className={x===id?"active":""} href={sitePath(`/characters/${x}?lang=${lang}`)}><img src={sitePath(`/icons/${x}.svg`)} alt={profiles[x].roman}/></a>)}</aside>
   <div className="profile-portrait-col"><div className={`portrait profile-portrait portrait-${id}`}><div className="portrait-splashes" aria-hidden="true"><i/><i/><i/><i/></div><img className="character-art" src={sitePath(`/characters/${id}.png`)} alt={`${p.name} ${p.roman}`}/></div></div>
   <article className="profile-card"><div className="package-hole" aria-hidden="true"/><h1>{en?p.roman:p.name}<i>{en?"":p.roman}</i></h1><div className="profile-meta"><span><b>{en?"Age":"年齡"}</b>{p.age}</span><span><b>{en?"Species":"種族"}</b>{en?p.enSpecies:p.species}</span><span><b>{en?"Sex":"性別"}</b>{en?p.enSex:p.sex}</span>{p.height&&<span><b>{en?"Height: ":"身高："}</b>{p.height}</span>}<span><b>{en?"Job: ":"職業："}</b>{en?p.enJob:p.job}</span><span><b>{en?"Weapon: ":"武器："}</b>{en?p.enWeapon:p.weapon}</span></div><hr/><h2>{en?"Description":"人物個性"}</h2><p>{en?p.enIntro:p.intro}</p><hr/><div className="profile-swatches"><div><b>{en?"Ink color":"墨水顏色"}</b><span/><span/></div><div><b>{en?"Eye color":"眼睛顏色"}</b><span/><span/></div></div></article>
  </section>
  <section className="profile-story"><h2>{en?"Background story":"背景故事"}</h2><p>{en?p.enStory:p.story}</p>{p.extra&&<div className="profile-extra">{p.extra.map((section:any)=><article key={section.zh}><h3>{en?section.en:section.zh}</h3><ul>{(en?section.enItems:section.zhItems).map((item:string)=><li key={item}>{item}</li>)}</ul></article>)}</div>}</section>
 </main>
}
