"use client";
import { useEffect, useRef, useState } from "react";

function FluidHeader(){
 const ref=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{const canvas=ref.current;if(!canvas||matchMedia("(prefers-reduced-motion: reduce)").matches)return;let live=true;import("./vendor/webgl-fluid.mjs").then(({default:WebGLFluid})=>{if(!live)return;WebGLFluid(canvas,{TRIGGER:"hover",IMMEDIATE:true,AUTO:false,SIM_RESOLUTION:128,DYE_RESOLUTION:512,DENSITY_DISSIPATION:.015,VELOCITY_DISSIPATION:1.57,PRESSURE:1,PRESSURE_ITERATIONS:16,CURL:0,SPLAT_RADIUS:1,SPLAT_FORCE:950,SPLAT_COUNT:8,COLORFUL:false,SHADING:true,BACK_COLOR:{r:255,g:255,b:255},TRANSPARENT:false,BLOOM:false,SUNRAYS:false})});return()=>{live=false}},[]);
 return <canvas ref={ref} className="fluid-canvas" aria-hidden="true"/>;
}

const cast=[
{slug:"musubi",name:"結",roman:"MUSUBI",age:"21",kind:"章魚 · 女",enKind:"Octoling · Female",role:"黑客／前軍官",enRole:"Hacker / Former Officer",tone:"pink",intro:"熱情、任性又行動派的前章魚軍官。脫隊後抹去軍籍，醉倒街頭被纁撿回家，從此理直氣壯地住了下來。",enIntro:"A passionate, headstrong former Octarian officer. After erasing her military record, she was found drunk in the street by Yuuhi—and simply never left."},
{slug:"yuuhi",name:"纁",roman:"YUUHI",age:"19",kind:"魷魚 · 男",enKind:"Inkling · Male",role:"熊先生商會打工仔",enRole:"Grizzco Worker",tone:"orange",intro:"隨和又笨拙的少年。背著父親留下的巨額債務，從十四歲起就在商會打工。對善意總想加倍回應，卻常常忘了照顧自己。",enIntro:"An easygoing but awkward young Inkling. Burdened by his father's enormous debt, he has worked at Grizzco since he was fourteen—always repaying kindness, often forgetting himself."},
{slug:"shuu",name:"終",roman:"SHUU",age:"24",kind:"章魚 · 男",enKind:"Octoling · Male",role:"真格選手／前軍官",enRole:"Ranked Player / Former Officer",tone:"teal",intro:"冷靜沉穩、社交圓滑的前軍官。來到地面後成為頂尖真格選手，暗中調查熊先生商會，也終於找回失聯的妹妹。",enIntro:"A calm, socially adept former officer. On the surface he became an elite ranked player, quietly investigating Grizzco while searching for his missing sister."},
{slug:"akane",name:"茜",roman:"AKANE",age:"24",kind:"魷魚 · 女",enKind:"Inkling · Female",role:"真格選手",enRole:"Ranked Player",tone:"red",intro:"熱情開朗的真格選手，也是終的固定隊友。戀愛路總是一波三折，卻依然相信轟轟烈烈的心動就在下一場。",enIntro:"A bright, outgoing ranked player and Shuu's regular teammate. Romance keeps going wrong, but she still believes her next great love is only one match away."},
{slug:"sumire",name:"堇",roman:"SUMIRE",age:"23",kind:"章魚 · 女",enKind:"Octoling · Female",role:"軍醫",enRole:"Military Doctor",tone:"violet",intro:"寡言而天賦過人的地下軍醫。精準、冷靜，對流言不屑一顧；唯獨面對前戀人結，她的感情從來不夠克制。",enIntro:"A quiet, brilliant military doctor from underground. Precise and composed, she ignores rumors—but has never managed such restraint with her former lover, Musubi."},
{slug:"kumori",name:"曇",roman:"KUMORI",age:"22",kind:"魷魚 · 女",enKind:"Inkling · Female",role:"紡織企業千金",enRole:"Textile Heiress",tone:"pearl",intro:"溫婉優雅的纁的青梅竹馬。童年搬離尚興後失聯，多年後在蠻頹鎮重逢，卻發現他的身邊已經多了兩個章魚。",enIntro:"Yuuhi's gentle and elegant childhood friend. Years after moving away without goodbye, she meets him again in Splatsville—with two Octolings now at his side."}];
const events=[["17 年前","餘暉","纁的母親病逝，父親自此性情大變。"],["9 年前","相遇","纁與曇在尚興的公園相識。"],["7 年前","離別","曇隨家族搬離，兩人失去聯絡。"],["5 年前","負債","纁的父親失蹤；結與堇開始交往。"],["3 年前","裂痕","結與堇分手。"],["2 年前","地面","終脫離軍隊，來到地面生活。"],["1 年前","組隊","終與茜成為隊友，也在商會認識纁。"],["12 月","同居","結被纁撿回家照顧，兩人開始同居。"],["3 月","三人之家","討債人找上門，終提議一起搬家。"]];

export default function Home(){
 const [active,setActive]=useState(0),[lang,setLang]=useState<"zh"|"en">("zh"),c=cast[active],en=lang==="en";
 return <main>
  <nav className="nav" id="top"><a className="brand" href="#top"><span>CITRUSODA</span> OC ARCHIVE</a><div className="navlinks"><a href="#characters">CHARACTERS</a><a href="#story">STORY</a></div><button className="lang" onClick={()=>setLang(en?"zh":"en")} aria-label="Switch language"><span className={!en?"on":""}>中</span><span className={en?"on":""}>EN</span></button></nav>
  <section className="archive-title"><FluidHeader/><span>FAN CHARACTER DATABASE · 2026</span><h1>CITRUSODA<br/><i>OC ARCHIVE</i></h1></section>
  <section className="characters" id="characters"><header className="section-head"><span>01 / CAST</span><h2>{en?"CHARACTER FILES":"角色檔案"}</h2></header><div className="character-layout"><div className="tabs" role="tablist" aria-label="選擇角色">{cast.map((x,i)=><button key={x.roman} className={`${x.slug}${i===active?" active":""}`} onClick={()=>setActive(i)} role="tab" aria-selected={i===active} aria-label={`${x.name} ${x.roman}`}><img src={`/icons/${x.slug}.svg`} alt="" /><b>{x.roman}</b></button>)}</div><article className={`profile ${c.tone}`}><button className="switch prev" onClick={()=>setActive((active+cast.length-1)%cast.length)} aria-label="Previous character">‹</button><div className="portrait"><span>{c.name}</span><small>{c.roman}</small></div><button className="switch next" onClick={()=>setActive((active+1)%cast.length)} aria-label="Next character">›</button><div className="profile-copy"><div className="kicker">SELECTED FILE / 0{active+1}</div><h3>{c.name}<i>{c.roman}</i></h3><div className="stats"><span><small>AGE</small>{c.age}</span><span><small>SPECIES</small>{en?c.enKind:c.kind}</span><span><small>ROLE</small>{en?c.enRole:c.role}</span></div><p>{en?c.enIntro:c.intro}</p><a className="readmore" href={`/characters/${c.slug}?lang=${lang}`}>{en?"READ FULL PROFILE":"閱讀完整檔案"} <span>➜</span></a></div></article></div></section>
  <section className="story" id="story"><header className="section-head light"><span>02 / STORY</span><h2>{en?"TIDAL TIMELINE":"潮汐時間線"}</h2></header><div className="timeline">{events.map(([time,title,text],i)=><article key={time}><div className="line"><b>{String(i+1).padStart(2,"0")}</b></div><time>{time}</time><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <footer className="footer"><div className="brand"><span>CITRU</span>SODA</div><p>ORIGINAL CHARACTER ARCHIVE · FAN WORK</p><a href="#top">BACK TO TOP ↑</a></footer>
 </main>
}
