"use client";
import { useEffect, useState } from "react";
import {sitePath} from "./sitePath";
import Link from "next/link";
import {chapters} from "./comics/data";

const cast=[
{slug:"musubi",name:"結",roman:"MUSUBI",age:"21",kind:"章魚 · 女",enKind:"Octoling · Female",role:"黑客／前軍官",enRole:"Hacker / Former Officer",tone:"pink",intro:"前章魚軍官。脫隊後抹去軍籍，醉倒街頭後被纁撿回家，然後理直氣壯地住了下來。",enIntro:"A passionate, headstrong former Octarian officer. After erasing her military record, she was found drunk in the street by Yuuhi—and simply never left."},
{slug:"yuuhi",name:"纁",roman:"YUUHI",age:"19",kind:"魷魚 · 男",enKind:"Inkling · Male",role:"熊先生商會打工仔",enRole:"Grizzco Worker",tone:"orange",intro:"母親早逝，父親賭博後留下了高額債務。14歲開始在熊先生商會打工還債，某天晚上撿到了醉在路邊的結從此被纏上。",enIntro:"An easygoing but awkward young Inkling. Burdened by his father's enormous debt, he has worked at Grizzco since he was fourteen—always repaying kindness, often forgetting himself."},
{slug:"shuu",name:"終",roman:"SHUU",age:"24",kind:"章魚 · 男",enKind:"Octoling · Male",role:"真格選手／前軍官",enRole:"Ranked Player / Former Officer",tone:"teal",intro:"前章魚軍官，來到地面後脫隊。現役真格選手，同時暗中調查熊先生商會。",enIntro:"A calm, socially adept former officer. On the surface he became an elite ranked player, quietly investigating Grizzco while searching for his missing sister."},
{slug:"akane",name:"茜",roman:"AKANE",age:"24",kind:"魷魚 · 女",enKind:"Inkling · Female",role:"真格選手",enRole:"Ranked Player",tone:"red",intro:"熱情開朗的真格選手，終的固定隊友。戀愛路總是一波三折，卻依然相信轟轟烈烈的心動就在下一場。",enIntro:"A bright, outgoing ranked player and Shuu's regular teammate. Romance keeps going wrong, but she still believes her next great love is only one match away."},
{slug:"sumire",name:"堇",roman:"SUMIRE",age:"23",kind:"章魚 · 女",enKind:"Octoling · Female",role:"軍醫",enRole:"Military Doctor",tone:"violet",intro:"醫術天賦極高的章魚軍隊的軍醫，也是結的前女友。",enIntro:"A quiet, brilliant military doctor from underground. Precise and composed, she ignores rumors—but has never managed such restraint with her former lover, Musubi."},
{slug:"kumori",name:"曇",roman:"KUMORI",age:"22",kind:"魷魚 · 女",enKind:"Inkling · Female",role:"紡織企業千金",enRole:"Textile Heiress",tone:"pearl",intro:"纁的青梅竹馬。童年搬離尚興後失聯，多年後在蠻頹鎮重逢。",enIntro:"Yuuhi's gentle and elegant childhood friend. Years after moving away without goodbye, she meets him again in Splatsville—with two Octolings now at his side."}];
const latestComics=[...chapters].reverse().slice(0,3);

export default function Home(){
 const [active,setActive]=useState(0),[lang,setLang]=useState<"zh"|"en">("zh"),c=cast[active],en=lang==="en";
 useEffect(()=>{setLang(localStorage.getItem("site-language")==="en"?"en":"zh")},[]);
 return <main>
 <nav className="nav" id="top"><a className="brand" href="#top"><span>CITRUSODA</span> OC ARCHIVE</a><div className="navlinks"><a href="#characters">{en?"CHARACTERS":"角色介紹"}</a><a href="#story">{en?"COMICS":"漫畫合集"}</a><Link href={sitePath("/gallery")}>{en?"GALLERY":"繪畫合集"}</Link></div><button className="lang" onClick={()=>{const next=en?"zh":"en";setLang(next);localStorage.setItem("site-language",next);window.dispatchEvent(new Event("site-language-change"))}} aria-label="Switch language"><span className={!en?"on":""}>中</span><span className={en?"on":""}>EN</span></button></nav>
  <section className="archive-title"><div className="header-image-placeholder" aria-hidden="true"/><div className="header-overlay" aria-hidden="true"/><h1>CITRUSODA<br/><i>OC ARCHIVE</i></h1></section>
 <section className="characters" id="characters"><header className="section-head"><h2>{en?"01/ Character Files":"01/角色簡介"}</h2></header><div className="character-layout"><div className="tabs" role="tablist" aria-label="選擇角色">{cast.map((x,i)=><button key={x.roman} className={`${x.slug}${i===active?" active":""}`} onClick={()=>setActive(i)} role="tab" aria-selected={i===active} aria-label={`${x.name} ${x.roman}`}><img src={sitePath(`/icons/${x.slug}.svg`)} alt="" /><b>{x.roman}</b></button>)}</div><article className={`profile ${c.tone}`}><button className="switch prev" onClick={()=>setActive((active+cast.length-1)%cast.length)} aria-label="Previous character">‹</button><div key={c.slug} className={`portrait portrait-${c.slug}`}><div className="portrait-splashes" aria-hidden="true"><i/><i/><i/><i/></div><img className="character-art" src={sitePath(`/characters/${c.slug}.png`)} alt={`${c.name} ${c.roman}`} /><small>{c.roman}</small></div><button className="switch next" onClick={()=>setActive((active+1)%cast.length)} aria-label="Next character">›</button><div className="profile-copy"><h3 className={en?"english-character-name":undefined}>{en?c.roman:<>{c.name}<i>{c.roman}</i></>}</h3><div className="stats"><span><small>AGE</small>{c.age}</span><span><small>SPECIES</small>{en?c.enKind:c.kind}</span><span><small>ROLE</small>{en?c.enRole:c.role}</span></div><p>{en?c.enIntro:c.intro}</p><Link className="readmore" href={sitePath(`/characters/${c.slug}?lang=${lang}`)}>{en?"READ FULL PROFILE":"閱讀完整檔案"} <span>➜</span></Link><Link className="readmore relationship-link" href={sitePath("/relationships")}>{en?"VIEW RELATIONSHIP NETWORK":"查看人物關係網"} <span>➜</span></Link></div></article></div></section>
 <section className="story comic-preview" id="story"><header className="section-head light"><h2>{en?"02/ Story":"02/漫畫合集"}</h2></header><div className="comic-grid">{latestComics.map((chapter)=><Link className="comic-card" href={sitePath(`/comics/${chapter.slug}`)} key={chapter.number}><div className="comic-art-slot"><img src={sitePath(chapter.pages[0])} alt={`Chapter ${chapter.number} preview`} loading="lazy" /></div><div><small>{en?"LATEST STORY":"最新故事"}</small><h3>#{String(chapter.number).padStart(2,"0")} {en?chapter.enTitle:chapter.title}</h3></div></Link>)}</div><Link className="readmore story-button" href={sitePath("/comics")}>{en?"VIEW ALL COMICS":"查看全部漫畫"}<span>➜</span></Link></section>
 </main>
}
